[variables]
a = { type = "integer" }
b = { type = "integer" }
c = { type = "integer" }

[operations.add]
inputs = ["a", "b"]
outputs = ["c"]
library_call = { library = "./libadd.so", symbol = "add" }


