[package]
name = "lunar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
cc = "1.2.2"
chumsky = "0.9.3"
clap = { version = "4.5.23", features = ["derive"] }
crossbeam = "0.8.4"
libloading = "0.8.6"
logos = "0.14.2"
rand = "0.8.5"
thiserror = "2.0.3"
