[package]
name = "lunar"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
crossbeam = "0.8.4"
libffi = "3.2.0"
libloading = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
